import Head from "next/head";
import Image from "next/image";
import { MoneriumClient, AuthContext } from "@monerium/sdk";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: AuthContext) {
  const [authFlowUrl, setAuthFlowUrl] = useState<string | null>(null);
  const client = new MoneriumClient();
  const router = useRouter();

  // AuthContext is available in the browser
  useEffect(() => {
    const getAuthFlowUrl = async () => {
      let res = await client.getAuthFlowURI({
        client_id: "654c9c30-44d3-11ed-adac-b2efc0e6677d",
        redirect_uri: "https://www.example.com/your-application",
      });
      console.log(
        "%c res",
        "color:white; padding: 30px; background-color: darkgreen",
        res
      );

      setAuthFlowUrl(res);
    };
    console.log(
      "%c authFlowUrl",
      "color:white; padding: 30px; background-color: darkgreen",
      authFlowUrl
    );

    getAuthFlowUrl();
    return () => {
      /* cleanup */
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Hey there! {props?.name}</p>
          <p>Get started with the Monerium API</p>
        </div>

        <div className={styles.center}>
          <button
            className={styles.button}
            type="button"
            onClick={() => router.push(`${authFlowUrl}`)}
          >
            <Image
              className={styles.logo}
              src="https://monerium.app/icon.png"
              alt="Next.js Logo"
              width={400}
              height={400}
              priority
            />
          </button>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const server = new MoneriumClient();

  await server.auth({
    client_id: "e38f68c0-deac-11ed-8259-a200f4ed426d",
    client_secret:
      "028dbeb1a42d9cc573e4c45c2b1114425d4c9415abaf49137494f3c672ea8060",
  });

  // Pass AuthContext to the page via props
  return { props: await server.getAuthContext() };
}
