import Head from "next/head";
import Image from "next/image";
import { IBAN, MoneriumClient, Profile } from "@monerium/sdk";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

import { AUTH_FLOW_CLIENT_ID, AUTH_FLOW_REDIRECT_URL } from "@/constants";

export default function Home() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [iban, setIban] = useState<IBAN | null>(null);
  const [isAuthorized, setIsAuthorized] = useState(false);
  const [refreshToken, setRefreshToken] = useState<string | null>(null);
  const router = useRouter();

  const [sdk] = useState(() => {
    // Initialize the SDK
    return new MoneriumClient({
      environment: "sandbox",
      clientId: AUTH_FLOW_CLIENT_ID, // Your applications Authorization Code Flow 'client_id'
      redirectUri: AUTH_FLOW_REDIRECT_URL,
      debug: true,
    });
  });

  useEffect(() => {
    const connect = async () => {
      if (sdk) {
        try {
          setIsAuthorized(await sdk.getAccess());
        } catch (error) {
          console.error("Failed to get access:", error);
        } finally {
          // TODO: set loading state
          if (sdk?.bearerProfile) {
            // TODO: securely store the refresh token
            setRefreshToken(sdk.bearerProfile.refresh_token);
          }
        }
      }
    };

    connect();

    return () => {
      if (sdk) {
        sdk.disconnect();
      }
    };
  }, []);

  useEffect(() => {
    const reconnect = async (token: string) => {
      if (sdk) {
        try {
          setIsAuthorized(await sdk.getAccess(token));
        } catch (error) {
          console.error("Failed to get access:", error);
        } finally {
          // TODO: set loading state
          if (sdk?.bearerProfile) {
            // TODO: securely store the refresh token
            setRefreshToken(sdk.bearerProfile.refresh_token);
          }
        }
      }
    };
    if (refreshToken && !isAuthorized) {
      reconnect(refreshToken);
    }
  }, [sdk, refreshToken]);

  useEffect(() => {
    const getProfiles = async () => {
      try {
        const data = await sdk?.getProfiles();
        setProfile(data?.profiles?.[0]);
        console.log("Profile", profile);
      } catch (error) {
        console.error("Failed to get profile:", error);
      }
    };
    const getIbans = async () => {
      try {
        const data = await sdk?.getIbans();
        setIban(data?.ibans?.[0]);
        console.log("Ibans", data);
      } catch (error) {
        console.error("Failed to get ibans:", error);
      }
    };

    if (isAuthorized) {
      getProfiles();
      getIbans();
    }
  }, [isAuthorized]);

  return (
    <>
      <Head>
        <title>Monerium SDK Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://monerium.app/icon.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Hey there! {profile?.name}</p>
          <p>Get started with the Monerium API</p>
        </div>
        {isAuthorized && iban && (
          <div className={styles.ibanContainer}>
            <p>Your IBAN:</p>
            <div className={styles.iban}>
              <p>{iban.iban}</p>
            </div>
          </div>
        )}

        {!isAuthorized && (
          <button
            className={styles.connectBtn}
            type="button"
            onClick={() => sdk.authorize()}
          >
            <Image
              src="https://monerium.app/icon.png"
              alt="Monerium logo"
              width={24}
              height={24}
            />
            Connect to Monerium
          </button>
        )}

        {isAuthorized && (
          <button
            className={styles.revokeBtn}
            type="button"
            onClick={() => {
              sdk.revokeAccess();
              setIsAuthorized(false);
              setProfile(null);
            }}
          >
            Revoke access
          </button>
        )}
      </main>
    </>
  );
}
